services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx-server
    restart: always
    networks:
      - blogicum_net
    ports:
      - "8000:80"
    volumes:
      - ./blogicum/static:/static/
      - media:/media
      - ./nginx:/etc/nginx/conf.d
    command: >
      sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - django_blogicum

  django_blogicum:
    build: blogicum
    image: blogicum
    container_name: django-blogicum
    restart: always
    working_dir: /app
    command: "gunicorn -c gunicorn.py blogicum.wsgi"
    networks:
      - blogicum_net
    volumes:
      - sqlite_data:/app/data
      - media:/app/media
    expose:
      - 8000

networks:
  blogicum_net:
    driver: bridge

volumes:
  sqlite_data:
  media:

